export enum YaCAFilterEnum {
    'RADIO' = 'RADIO',
    'MEGAPHONE' = 'MEGAPHONE',
    'PHONE' = 'PHONE',
    'PHONE_SPEAKER' = 'PHONE_SPEAKER',
    'INTERCOM' = 'INTERCOM',
    'PHONE_HISTORICAL' = 'PHONE_HISTORICAL'
}